The next web branch
Godswilly/the-next-web pull request #2
Opened 2020-06-15 10:51 UTC by Alaska01

-This project consists of replicating the The Next Web website putting emphasis on how it behaves differently depending on the size of the screen where the website is rendered.
-You can find the original project specification at: https://www.theodinproject.com/courses/html5-and-css3/lessons/building-with-responsive-design, but bear in mind that the design pattern for this site changes frequently, hence every detail upon submit might not look similar to the current one. The pictures are the major aspects that changes. Our site was responsive on all screens.

2020-06-16 00:54 UTC, trekab requested changes
# Changes Required! :tada: 
Hi @Alaska01 and @Godswilly! Well done with this project so far. There are some changes to need to consider in order to complete this project. These include;
- [ ] Your clone is broken for screens larger than 1440px. [Screenshot](https://github.com/trekab/images/blob/master/img/Aye/next_web.png?raw=true)
- [ ] On medium screens, your main navigation row has unnecessary white space(margin) on the rightmost end and left most end.
- [ ] The top 3 articles section:
  - On large and medium screens, the two smaller images on the rightmost part of the row (one above another) should have a smaller font compared to the bigger image on the left-most part.
  - On medium screens, the TWN logo should disappear ([link to page](https://thenextweb.com/)).
  - For large and medium screens, your text is not aligned appropriately. It should be aligned to the bottom left corners of the images.
- [ ] Your `Latest news` section is different from the original page on small screen sizes.
[Your clone](https://github.com/trekab/images/blob/master/img/Aye/latest_news_clone.png?raw=true) Vs [Original page](https://github.com/trekab/images/blob/master/img/Aye/latest_news.png?raw=true)
- [ ] The footer should not change through the break-points.
- [ ] Your CSS styles should use [media queries](https://www.w3schools.com/css/css_rwd_mediaqueries.asp) for 2 breakpoints ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/responsive_design/breakpoints_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59540217/)). 
  - No small breakpoint as it is mobile-first and the base styles should be for the mobile screen. ([Screenshot on mobile-first approach](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/responsive_design/mobile_first.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59540217/)) 
  - medium: min-width around 768px
  -  large: min-width 1024px

__Kindly make the necessary changes and submit another code review request.__
_Feel free to reach me on slack for any inquiries about this review._ :wink: 
__Treasure Kabareebe__
[GitHub](https://github.com/trekab) | [LinkedIn](https://www.linkedin.com/in/treasure-kabareebe/) | [Twitter](https://twitter.com/TKabareebe)

2020-06-16 20:42 UTC, Alaska01 commented
Made all the required changes  as requested by TSE. Kindly remember this site is progressive as updates are posted frequently by the developers.

2020-06-17 00:01 UTC, BrittanyBlake requested changes
### Status: Changes Required ♻️ 
****
### Hi @Alaska01  and @Godswilly ! 👋 
You have done a great job implementing the changes requested by the previous TSE! 👍 You have also done a wonderful job with your project so far! 💪 👏  There are just a few issues that need to be resolved before you can move on: ⬇️ 
****
- [ ] This project should not contain any media queries for the small screen as it is a mobile-first design. This was pointed out to you by the previous TSE. Please fix this.
![Screen Shot 2020-06-17 at 2 00 18 AM](https://user-images.githubusercontent.com/48804258/84839861-4fb5d900-b03e-11ea-9c49-f745b42e2b4e.png)

- [ ] There is a horizontal scroll on your page on the medium and small screen sizes. Please fix this.
![Screen Shot 2020-06-16 at 11 32 07 PM](https://user-images.githubusercontent.com/48804258/84839032-4deb1600-b03c-11ea-9c47-aee2b46942f0.png)





- **The top 3 articles section:**

- [ ] The text on the image in the bottom right of this section is overlapping on the medium screen. Please compare your clone with the original page and fix this. 
Your clone 👇 
![Screen Shot 2020-06-16 at 11 33 27 PM](https://user-images.githubusercontent.com/48804258/84839179-b2a67080-b03c-11ea-8e35-726cf8983b9b.png)
The image that I am referring to 👇 
![Screen Shot 2020-06-16 at 11 33 41 PM](https://user-images.githubusercontent.com/48804258/84839180-b3d79d80-b03c-11ea-88fe-e4a956f9eb5c.png)
The original page 👇 
![Screen Shot 2020-06-16 at 11 33 46 PM](https://user-images.githubusercontent.com/48804258/84839181-b3d79d80-b03c-11ea-9c51-48dbae68caed.png)

- [ ] The text on the first image in this section on the small screen is also overlapping. 
      - It may be hard to see here but "Tech" is overlapping with "Divider"


Your clone 👇 
![Screen Shot 2020-06-17 at 1 50 43 AM](https://user-images.githubusercontent.com/48804258/84839326-16c93480-b03d-11ea-8864-1219a4601dd7.png)
The original page 👇 
![Screen Shot 2020-06-17 at 1 51 49 AM](https://user-images.githubusercontent.com/48804258/84839342-1fba0600-b03d-11ea-8129-6aa6989de107.png)

- **Footer**

- [ ] As was pointed out to you by the previous TSE, the footer should not change with the breakpoints. In your project, the footer is not properly aligned on the medium screen. Please compare your clone with the original and fix this. 
Project requirements 👇 
![Screen Shot 2020-06-17 at 1 56 05 AM](https://user-images.githubusercontent.com/48804258/84839602-bb4b7680-b03d-11ea-8b47-8a51ea09fdfc.png)
Your clone 👇 
![Screen Shot 2020-06-17 at 1 38 26 AM](https://user-images.githubusercontent.com/48804258/84839640-dae29f00-b03d-11ea-899a-fe206867753c.png)
The original page 👇 
![Screen Shot 2020-06-17 at 1 38 49 AM](https://user-images.githubusercontent.com/48804258/84839657-e46c0700-b03d-11ea-951d-0ff9cce1cb6f.png)








****
### Please make the required changes and resubmit for a new code review once you are ready 🙏

Good Luck and Happy Coding 🍀 👩🏾‍💻

_P.S. If you have any questions about my review or need help, you can message me on slack (@ Brittany Blake)._

2020-06-17 12:07 UTC, Alaska01 commented
Many thanks for the feedback on the reviews. We have done it the way you asked. Well, we are learning and are always very happy to get more knowledge. 

All changes have been made as required. We would be ever willing to look at some suggestions that you may have. Kindly consider the points below as well.

Kindly use the Mozilla Firefox developers tools instead of Google Chrome to see that the site is not overflowing on mobile, that problem is specific to the Chrome developers tool. We currently have do not have control over that; it's a bug at their end.

It would be great if you can share with us where it is a fixed rule that mobile-first should not have a media query. We would be thrilled to update our knowledge. But looking at W3School and Free Code Camp, it seems apparent that one can set as many breaking points for design. It is even best practice to have numerous breaking point beyond just two. Here are some resources from leading industry professionals we were following (https://www.w3schools.com/css/css_rwd_mediaqueries.asp, https://www.freecodecamp.org/news/the-100-correct-way-to-do-css-breakpoints-88d6a5ba1862/).

We may be wrong with our knowledge of grammar, but the last time we checked a "HINT" does not translate into a fixed rule that must be followed. As we are always saying, we are newbies in the programming world, feel free to educate us on anything we don't know but feel we should be conversant in such areas. We are always open to suggestions and learning. Thank you very kindly.

2020-06-17 18:53 UTC, addod19 commented
## Pull Request under review by Daniel Larbi Addo (TSE)

2020-06-17 18:55 UTC, addod19 requested changes
## Status: Require changes :recycle: :traffic_light: 

Hi **TEAM**, great job on fixing some of the comments made by the previous TSE :+1: However, I would like to highlight some of the comments made earlier so we can fix it and get our project approved. Kindly find comments below:
- ``` Mobile-first design ```, In mobile-first design, we do not need a media query. Let us remove the media query and fix the issue as pointed out earlier
- ``` Horizontal scroll ```, as developers, we create an application to fit on all browsers. So a quick fix for the horizontal scroll would be to set the main container width to 100% :slightly_smiling_face: 

Kindly make these changes and submit another code review :smile: 
_Happy coding_ :man_technologist: 
[Daniel Larbi Addo](https://www.linkedin.com/in/daniel-larbi-addo/)

2020-06-18 18:21 UTC, Alaska01 commented
Fixed the issues as requested by the TSE. Thanks for the feedback it was useful. If at all the google developers tool are misbehaving try opening it on real devices, the live link works fine. I hope this works perfect at your end too. Thanks.

2020-06-18 19:25 UTC, tirthajyoti-ghosh requested changes
# Status: Changes required 🚨

## Nice job making the changes 👌🙌👏

### But we need to make some more changes.

- I see that you have forgotten to exclude the `node-modules` folder when committing. Remember to add that folder in your `.gitignore` file. Also, remove the folder from your repo.

- Let's make sure that we have the TNW logo in large screens

### Clone

![image](https://user-images.githubusercontent.com/57726348/85059926-0b534600-b1c2-11ea-9c3d-6d92dbaac99a.png)

### Original

![image](https://user-images.githubusercontent.com/57726348/85060691-4b66f880-b1c3-11ea-8a06-77a3d33e4810.png)

- The title must come down. Right now it has extra space below it. Also, you are missing the category over the title.

### Clone

![Annotation 2020-06-19 002549](https://user-images.githubusercontent.com/57726348/85061100-e52ea580-b1c3-11ea-80dd-af1d418334d6.jpg)

### Original

![Annotation 2020-06-19 002629](https://user-images.githubusercontent.com/57726348/85061118-ec55b380-b1c3-11ea-897b-3c4f0c3c5420.jpg)

- Let's also add some space below each section -> `top 3 articles`, `latest news`, `latest funding`, `apps, gear, tech, ...` and `latest deals`.

- Elements here are squeezed together. Add some space around them.

### Clone

![Annotation 2020-06-19 004756](https://user-images.githubusercontent.com/57726348/85062731-9f271100-b1c6-11ea-959d-27cb134396a8.jpg)

### Original

![Annotation 2020-06-19 004827](https://user-images.githubusercontent.com/57726348/85062757-ab12d300-b1c6-11ea-9a9a-9fcb23d802ad.jpg)

- The list items are squeezed together in `apps, gear, tech,...` section. Let's add some padding to them.

### Clone

![Annotation 2020-06-19 003503](https://user-images.githubusercontent.com/57726348/85061716-e7ddca80-b1c4-11ea-81af-19b4f2c3370a.jpg)

### Original

![Annotation 2020-06-19 003529](https://user-images.githubusercontent.com/57726348/85061730-ef04d880-b1c4-11ea-964a-e9af085d21f0.jpg)

- The image and the title in `latest deals` are not aligned properly.

### Clone

![Annotation 2020-06-19 004249](https://user-images.githubusercontent.com/57726348/85062369-ff698300-b1c5-11ea-9fee-951d62dff891.jpg)

### Original

![Annotation 2020-06-19 004317](https://user-images.githubusercontent.com/57726348/85062413-0f816280-b1c6-11ea-9cf1-bac8098294be.jpg)

- There are couple of invalid CSS properties. I have pointed them out in the comments below.

Overall, you have done a great job with this project. Apply the suggested changes and request another review.

Happy coding 👨‍💻

2020-06-18 19:27 UTC, tirthajyoti-ghosh commented on css/style.css
> +  background-color: red 5px solid;
This is an invalid property. `background-color` only takes color values. If you want to add other background properties, use the shorthand `background` property.

2020-06-18 19:29 UTC, tirthajyoti-ghosh commented on css/style.css
> +  margin-top: auto auto;
Invalid property. `margin-top` only takes one value.

2020-06-18 19:30 UTC, tirthajyoti-ghosh commented on css/style.css
> +    margin-top: 10px 10px;
Invalid property. `margin-top` only takes one value.

2020-06-18 19:31 UTC, tirthajyoti-ghosh commented on css/style.css
> +    margin-top: 10px 10px;
Invalid property. `margin-top` only takes one value.

2020-06-18 19:33 UTC, tirthajyoti-ghosh reviewed
Apply these changes and request another code review.

Happy coding 👨‍💻

2020-06-19 13:13 UTC, HADDADSOHAIB requested changes
### Status: Change Required :recycle: 

### Hello @Alaska01     :hand: 

### Good job your project is getting better and better. :+1: 

### Unfortunately, there are still one change that must be done to get the project approved:

![Screenshot from 2020-06-19 14-00-51](https://user-images.githubusercontent.com/26064042/85135185-9f122a00-b235-11ea-9b06-8e2fcb9c9646.png)
You add the node module to gitignore, but you need also to remove it from the repository.
- You have commented code in you HTML, remove that.
### Once you are done, ask for another code review

2020-06-19 13:46 UTC, Alaska01 commented
Removed HTML comments and node modules from repo

2020-06-19 18:50 UTC, christianotieno approved these changes
# PROJECT APPROVED :champagne:
Good job working on the changes :fireworks: 
##
***All the required tasks have been fulfilled in this project. I will go ahead and mark this as complete.***
- Congratulations on the splendid job :+1:
- You can now merge this. I wish you all the very best in your next tasks 🥇 
##
Happy coding :smile:
**[Christian Otieno](https://github.com/ChristianOtieno)**
[Twitter](https://twitter.com/iamchrisotieno) [linkedin](https://www.linkedin.com/in/christianotieno/) [GitLab](https://gitlab.com/christianotieno)

2020-06-19 19:04 UTC, merged